Splitted scripts into multiple directories

diff --git a/bin/scripts/pdocker b/bin/scripts/pdocker
--- a/bin/scripts/pdocker
+++ b/bin/scripts/pdocker
@@ -1,9 +1,9 @@
 #!/bin/bash
 
-source ./utils
+source /home/conni/bin/scripts/utils
 
 if [ $# -eq 0 ]; then
-	err "Error provice a docker image" || return 1
+	err "Error provice a docker image" || exit 1
 fi
 
 sudo docker -run -v 'pwd':'pwd' -w 'pwd' -i -t $1 /bin/bash
