chore: reformat all scripts

diff --git a/bin/scripts/pdocker b/bin/scripts/pdocker
--- a/bin/scripts/pdocker
+++ b/bin/scripts/pdocker
@@ -3,7 +3,7 @@
 . "${HOME}"/bin/scripts/utils
 
 if [ $# -eq 0 ]; then
-	err "Error provice a docker image" || exit 1
+  err "Error provice a docker image" || exit 1
 fi
 
 docker run -ti --rm -v $(pwd):/tmp "${1}" /bin/bash
